const $=s=>document.querySelector(s), money=n=>`$${Number(n).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`, pct=n=>`${(Number(n)*100).toFixed(2)}%`;let opportunities=[];
async function json(url,opts){const r=await fetch(url,opts);if(!r.ok)throw new Error((await r.json()).detail||r.statusText);return r.json()}
function status(name,data){const key=name.toLowerCase(),on=data.connected;$('#'+key+'-dot').classList.toggle('on',on);$('#'+key+'-status').textContent=on?'CONNECTED':'DISCONNECTED';$('#'+key+'-time').textContent=data.last_update?new Date(data.last_update).toLocaleTimeString():''}
async function load(){try{const [h,d]=await Promise.all([json('/api/health'),json('/api/dashboard')]);$('#mode').textContent=h.mode;status('poly',h.exchanges.POLYMARKET);status('kalshi',h.exchanges.KALSHI);$('#markets').textContent=d.markets_monitored;$('#matches').textContent=d.matched_markets;$('#opps').textContent=d.live_opportunities;$('#capital').textContent=money(d.capital_deployable);$('#profit').textContent=money(d.potential_net_profit);$('#updated').textContent='UPDATED '+new Date().toLocaleTimeString();opportunities=d.opportunities;render()}catch(e){toast(e.message,true)}}
function leg(l){return `<b>${l.exchange}</b><span class="sub">BUY ${l.outcome} · ${money(l.vwap)} × ${l.quantity.toFixed(2)}</span>`}
function render(){const body=$('#rows');if(!opportunities.length){body.innerHTML='<tr><td colspan="8" class="event">No positive depth-aware candidates currently pass initial economics.<span class="sub">Rejected and non-profitable baskets are never presented as opportunities.</span></td></tr>';return}body.innerHTML=opportunities.map((o,i)=>`<tr data-i="${i}"><td class="event">${o.event}<span class="sub">${o.strategy.replaceAll('_',' ')}</span></td><td>${leg(o.legs[0])}</td><td>${leg(o.legs[1])}</td><td class="positive">${pct(o.net_roi)}</td><td>${money(o.capacity)}</td><td class="positive">${money(o.net_profit)}</td><td><span class="badge ${o.classification}">${o.classification}</span><span class="sub">MATCH ${o.match_confidence}</span></td><td>${o.freshness_seconds.toFixed(0)}s</td></tr>`).join('');body.querySelectorAll('tr').forEach(r=>r.onclick=()=>detail(opportunities[+r.dataset.i]))}
function detail(o){const legs=o.legs.map((l,i)=>`<div class="card"><h3>LEG ${String.fromCharCode(65+i)} · ${l.exchange}</h3><div class="statline"><span>Contract</span><b>${l.market_id}</b></div><div class="statline"><span>Side</span><b>BUY ${l.outcome}</b></div><div class="statline"><span>VWAP</span><b>${money(l.vwap)}</b></div><div class="statline"><span>Quantity / levels</span><b>${l.quantity.toFixed(2)} / ${l.levels_used}</b></div><div class="statline"><span>Fee</span><b>${money(l.fee)}</b></div></div>`).join('');$('#detail-body').innerHTML=`<div class="detail"><div class="eyebrow">${o.strategy.replaceAll('_',' ')}</div><h2>${o.event}</h2><div class="grid">${legs}</div><div class="card analysis"><h3>EXECUTABLE ECONOMICS</h3>${[['Gross cost',o.capital_required-o.fees],['Fees',o.fees],['Depth slippage vs top',o.slippage],['Minimum payout',o.minimum_payout],['Net profit',o.net_profit],['Net ROI',pct(o.net_roi)],['Maximum modeled size',o.quantity.toFixed(2)+' contracts']].map(x=>`<div class="statline"><span>${x[0]}</span><b>${typeof x[1]==='number'?money(x[1]):x[1]}</b></div>`).join('')}</div><div class="card analysis"><h3>MATCH ANALYSIS · ${o.match_confidence} (${(o.match_score*100).toFixed(0)}%)</h3><ul>${o.match_reasons.map(x=>`<li>${x}</li>`).join('')}${o.resolution_differences.map(x=>`<li class="danger">${x}</li>`).join('')}${o.rejection_reasons.map(x=>`<li class="danger">Risk gate: ${x}</li>`).join('')}</ul></div><button class="execute" data-id="${o.id}">SIMULATE EXECUTION · PAPER ONLY</button></div>`;$('#detail').showModal();$('.execute').onclick=async e=>{try{const t=await json('/api/paper/'+e.target.dataset.id,{method:'POST'});toast('Simulation recorded: '+t.status);$('#detail').close();loadPerformance()}catch(x){toast(x.message,true)}}}
async function loadPerformance(){const p=await json('/api/paper/performance');$('#p-total').textContent=p.total_simulations;$('#p-capital').textContent=money(p.capital_deployed);$('#p-profit').textContent=money(p.theoretical_profit);$('#p-roi').textContent=pct(p.average_roi);$('#p-failed').textContent=p.failed_hedge_simulations;$('#ledger').innerHTML=p.trades.length?p.trades.map(t=>`<div class="item"><span>${new Date(t.timestamp).toLocaleString()}</span><b>${t.status}</b><span>${t.quantity.toFixed(2)} qty</span><span>${money(t.capital_deployed)}</span><span class="positive">${money(t.theoretical_profit)}</span></div>`).join(''):'No simulations recorded yet.'}
function toast(msg,bad=false){const t=$('#toast');t.textContent=msg;t.style.borderColor=bad?'var(--red)':'var(--green)';t.style.display='block';setTimeout(()=>t.style.display='none',3500)}
$('#refresh').onclick=async()=>{await json('/api/refresh',{method:'POST'});load()};$('.close').onclick=()=>$('#detail').close();document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');const perf=t.dataset.view==='performance';$('#scanner').hidden=perf;$('#performance').hidden=!perf;if(perf)loadPerformance()});load();setInterval(load,30000);

